### ISSUE TITLE
Slow initialization for large-scale scenarios

### ISSUE THREAD

**Issue by fmxFranky** [salesforce/warp-drive#64]
It will be very slow when initializing  large-scale scenarios (e.g. 512 taggers and 1024 runners) in tag_continuous environment. How  to accelarate the initialization?

**Comment by Emerald01** [comment]
It is expected that the initialization would not be fast in general because the initialization pushes all the host data to the GPU.

In your case, I can imagine you at least push a few GB data from CPU to GPU, it takes time, but it only happens once. When it is done, there will be 0 data transfer in the following steps. 

For your setting, if it is 512 + 1024 agents, it also exceeds the maximum number of threads (which is 1024) in one single block, so WarpDrive will automatically assign 2 blocks for each environment, all those delicate settings will increase the compilation time a little bit as well. 

To replicate your scenario, I simply used this setting, and it takes me about 2.5 minutes to initialize, which is normal.
```
env:
    num_taggers: 512
    num_runners: 1024
    grid_length: 20.0
    episode_length: 500
    max_acceleration: 0.1
    min_acceleration: -0.1
    max_turn: 2.356 # 3*pi/4 radians
    min_turn: -2.356 # -3*pi/4 radians
    num_acceleration_levels: 20
    num_turn_levels: 20
    skill_level_runner: 1.0
    skill_level_tagger: 1.0
    max_speed: 1.0
    seed: 274880
    use_full_observation: False
    runner_exits_game_after_tagged: True
    num_other_agents_observed: 10
    tag_reward_for_tagger: 10.0
    tag_penalty_for_runner: -10.0
    step_penalty_for_tagger: 0.0
    step_reward_for_runner: 0.0
    edge_hit_penalty: 0.0
    end_of_game_reward_for_runner: 1.0
    tagging_distance: 0.02
# Trainer settings
trainer:
    num_envs: 2 # number of environment replicas
    num_episodes: 100 # number of episodes to run the training for. Can be arbitrarily high!
    train_batch_size: 250 # total batch size used for training per iteration (across all the environments)
```
