### ISSUE TITLE
Using a custom policy model

### ISSUE THREAD

**Issue by Finebouche** [salesforce/warp-drive#69]
Hello ! 

I was wondering how to save and use a new policy template? How to do this for an Environment is well explained in the tutorials, however I haven't found a way to do something similar with a custom Policy. 

For instance if I want to create an alternative to [fully_connected.py](https://github.com/salesforce/warp-drive/blob/master/warp_drive/training/models/fully_connected.py) in my project, I would like to create a custom_connected.py file with
```
class CustomConnected(nn.Module):
    blablabla
```
How do I use this ?

**Comment by Emerald01** [comment]
Thank you for the suggestion, we will improve the tutorials to include this part.

The idea is that the Policy model written by Pytorch is just a normal Pytorch model with a forward() method. Because all the training batches are torch.Tensor objects provided by WarpDrive, you can imagine the model part has no much difference from a Python step() function. There are a few definitions and slight differences you may need to pay attention to, 

In the forward(), 
(1) we return `action_probs`, `vals`. Here, the `action_probs` is a list of the size of action types.
(2) we have push the observation to the batch, it sounds a little bit strange, but this is necessary. Since we are dealing with a high dim observation array, we will flatten out the observation inside the forward function, and copy it to the batch for the later use.

**Comment by Finebouche** [comment]
Oh thank you, 
I guess my question was more how to use the then created model in the enwrapper ? I will try to make it more clear what I mean by that. 

In [this tutorial](https://github.com/salesforce/warp-drive/blob/master/tutorials/tutorial-5-training_with_warp_drive.ipynb) the a dictionary is defined as : 
```
# Policy network settings
policy: # list all the policies below
    runner:
        to_train: True # flag indicating whether the model needs to be trained
        algorithm: "A2C" # algorithm used to train the policy
        gamma: 0.98 # discount rate gamms
        lr: 0.005 # learning rate
        vf_loss_coeff: 1 # loss coefficient for the value function loss
        entropy_coeff:
        - [0, 0.5]
        - [2000000, 0.05]
        model: # policy model settings
            type: "fully_connected" # HERE I WOULD LIKE TO REPLACE WITH MY CUSTOM MODEL I GUESS ? 
            fc_dims: [256, 256] # dimension(s) of the fully connected layers as a list
            model_ckpt_filepath: "" # filepath (used to restore a previously saved model)
    tagger:
        to_train: True
        algorithm: "A2C"
        gamma: 0.98
        lr: 0.002
        vf_loss_coeff: 1
        model:
            type: "fully_connected"
            fc_dims: [256, 256]
            model_ckpt_filepath: ""
```
but this string that we define is not used in the next steps of the tutorial.

For instance this block :
```
# Agents can share policy models: this dictionary maps policy model names to agent ids.
policy_tag_to_agent_id_map = {
    "tagger": list(env_wrapper.env.taggers),
    "runner": list(env_wrapper.env.runners),
}
```
doesn't use the previously defined string. 

I am afraid to just miss something obvious here.

**Comment by Emerald01** [comment]
The configure is used, the following just told the wrapper what agent ids are taggers and runners, and the corresponding ids will pick up the configure accordingly.

```
policy_tag_to_agent_id_map = {
    "tagger": list(env_wrapper.env.taggers),
    "runner": list(env_wrapper.env.runners),
}
```

**Comment by Finebouche** [comment]
Yes ! Then for instance I have to policy network as `custom_policy1.py` and  `custom_policy2.py` that I implemented using a normal Pytorch model and taking into account your recommendation. I then change my configure string to : 
```yaml
# Policy network settings
policy: # list all the policies below
    runner:
...
        model: # policy model settings
            type: "custom_policy1"  
            ...
    tagger:
...
        model:
            type: "custom_policy2"
            ...
```

I get the following error message 
```python
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[30], line 1
----> 1 trainer = Trainer(env_wrapper, run_config, policy_tag_to_agent_id_map)

File /project_ghent/warpdrive_env/lib/python3.8/site-packages/warp_drive/training/trainer.py:273, in Trainer.__init__(self, env_wrapper, config, policy_tag_to_agent_id_map, create_separate_placeholders_for_each_policy, obs_dim_corresponding_to_num_agents, num_devices, device_id, results_dir, verbose)
    271 for policy in self.policies:
    272     self.current_timestep[policy] = 0
--> 273     self._initialize_policy_model(policy)
    275 # Load the model parameters (if model checkpoints are specified)
    276 # Note: Loading the model checkpoint may also update the current timestep!
    277 self.load_model_checkpoint()

File /project_ghent/warpdrive_env/lib/python3.8/site-packages/warp_drive/training/trainer.py:375, in Trainer._initialize_policy_model(self, policy)
    366     model = FullyConnected(
    367         self.cuda_envs,
    368         policy_model_config["fc_dims"],
   (...)
    372         self.obs_dim_corresponding_to_num_agents,
    373     )
    374 else:
--> 375     raise NotImplementedError
    376 self.models[policy] = model

NotImplementedError: 
```

So I guess there is an extra step that I need to do to implement a custom model
